title: Ian McNerlin
description: Platform & IoT Engineering
url: "https://ikmcn.github.io"
baseurl: ""
author: Ian McNerlin
email: ""
github_username: ikmcn

permalink: /:title/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  
future: true
